lagou_new_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myapp.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name = 'index'),
    url('^users/', include('users.urls', namespace = "users")),
    url(r'^index1/$', IndexView1.as_view(), name = 'index1'),
    url(r'^index2/$', IndexView2.as_view(), name = 'index2'),
    url(r'^index3$', IndexView3.as_view(), name = 'index3'),
    url(r'^index4$', IndexView4.as_view(), name = 'index4'),
    url(r'^index5$', IndexView5.as_view(), name = 'index5'),
    url(r'^index6$', IndexView6.as_view(), name = 'index6'),
    url(r'^index7$', IndexView7.as_view(), name = 'index7'),
]

users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__version__ = '1.0.0.0'
from django.conf.urls import url
from .views import LoginView, RegisterView,LogoutView


"""
@brief 简介 
@details 详细信息
@author  zhphuang
@data    2018-03-28 
"""

urlpatterns = [
    url(r'login/', LoginView.as_view(), name="login"),
    url(r'logout/', LogoutView.as_view(), name="logout"),
    url('register/', RegisterView.as_view(), name="register"),
]

myapp/models.py
from django.db import models

# Create your models here.


class DataModel(models.Model):
    company_name = models.CharField(verbose_name = '公司名称', max_length = 256)
    zhiwei = models.CharField(verbose_name = '职位', max_length = 256)
    position = models.CharField(verbose_name = '地理位置', max_length = 256)
    money = models.CharField(verbose_name = '薪资范围', max_length = 256)
    exp = models.CharField(verbose_name = '经验', max_length = 256)
    xueli = models.CharField(verbose_name = "学历", max_length = 10)
    industry = models.CharField(verbose_name = '行业', max_length = 256)
    rongzi = models.CharField(verbose_name = "融资阶段", max_length = 10)
    skill_type = models.IntegerField(verbose_name = '技术类型', choices = ((0,"后端开发"),
                                                                       (1, "移动开发"),
                                                                       (2, "前端开发"),
                                                                       (3, "人工智能"),
                                                                       (4, "测试"),
                                                                       (5, "运维"),
                                                                       (6, "数据库")
                                                                      ))
    sort = models.IntegerField(verbose_name = "类型", choices = ((0, "java"), (1, "c++"), (2, "php"),(3, 'python'),
                                                               (4, "HTML5"), (5, "android"), (6, "ios"), (7, "wp"),
                                                               (8, "web前端"), (9, "Flash"), (10, "html5"), (11, "javascript"),
                                                               (12, "深度学习"), (13, "机器学习"), (14, "图像处理"), (15, "图像识别"),
                                                               (16, "测试工程师"), (17, "自动化测试"), (18, "功能测试"), (19, "性能测试"),
                                                               (20, "运维工程师"), (21, "运维开发工程师"), (22, "网络工程师"), (23, "系统工程师"),
                                                               (24, "mysql"), (25, "sqlserver"), (26, "oracle"), (27, "DB2")
                                                               ))

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block customstyle %}
    <script type="text/javascript" src="http://libs.baidu.com/jquery/2.1.1/jquery.min.js"></script>
    <script language="JavaScript" type="text/javascript" src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js" charset="utf-8"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <style type="text/css">
        body{overflow-x:hidden; background:#f2f0f5;}
        #main-tab {
            border: 1px solid #eaeaea;
            background: #FFF;
            font-size: 12px;
            margin: auto;
        }
        tbody {
            display: table-row-group;
            vertical-align: middle;
            border-color: inherit;
        }
        tr {
            display: table-row;
            vertical-align: inherit;
            border-color: inherit;
        }
        #main-tab td {
            font-size: 14px;
            line-height: 50px;
        }
        .borderright{ border-right:1px solid #ebebeb}
        .borderbottom{ border-bottom:1px solid #ebebeb}
        table {
            border-collapse:collapse;
            border-spacing:0;
            font-size:14px;
        }
        caption,th {
            text-align:left;
        }
        td.fenye{ padding:10px 0 0 0; text-align:right;}
    </style>
{% endblock %}
{% block content %}
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#panel-8023" id="a-8023" data-toggle="tab">职位查看</a>
        </li>
        <li>
            <a href="#panel-554542" id="a-554542" data-toggle="tab">职位分析</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="panel-8023">
            <div class="row" style="margin-bottom:5px;">
<div>
<table width="80%" border="0" cellspacing="0" cellpadding="0" id="main-tab">
    <th>
        <tr style="background-color: #39445c;color: white;">

            <td align="center" valign="middle" class="borderright borderbottom">职位</td>
            <td align="center" valign="middle" class="borderright borderbottom">薪资范围</td>
            <td align="center" valign="middle" class="borderright borderbottom">公司名称</td>
            <td align="center" valign="middle" class="borderright borderbottom">公司融资</td>
            <td align="center" valign="middle" class="borderright borderbottom">地理位置</td>
            <td align="center" valign="middle" class="borderright borderbottom">工作经验</td>
            <td align="center" valign="middle" class="borderright borderbottom">所属行业</td>
            <td align="center" valign="middle" class="borderright borderbottom">学历</td>
            <td align="center" valign="middle" class="borderright borderbottom">类型</td>
        </tr>
    </th>

    {% for item in paginator.object_list %}
    <tr onMouseOut="this.style.backgroundColor='#ffffff'" onMouseOver="this.style.backgroundColor='#edf5ff'">
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.zhiwei }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.money }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.company_name }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.rongzi }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.position }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.exp }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.industry }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.xueli }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.get_skill_type_display}}</td>
    </tr>
    {% endfor %}

</table>
</div>
<div style="width: 80%;margin: auto">
 <ul class="pagination pagination-lg">
    {% if paginator.has_previous %}
        <li>
            <a href="{% url 'index' %}?page={{ paginator.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">上一页</span>
            </a>
        </li>
    {% else %}
        <li class="disabled">
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">上一页</span>
            </a>
        </li>
    {% endif %}

    {% for number in paginator.paginator.pager_num_range %}
        {% if number == paginator.number %}
            <li class="active"><a href="{% url 'index' %}?page={{ number }}">{{ number }}</a></li>
        {% else %}
            <li><a href="{% url 'index' %}?page={{ number }}" >{{ number }}</a></li>
        {% endif %}
    {% endfor %}
    {% if paginator.has_next %}
        <li>
            <a href="{% url 'index' %}?page={{ paginator.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">下一页</span>
            </a>
        </li>
    {% else %}
        <li class="disabled">
            <a href="#" aria-label="Next">
                <span aria-hidden="true">下一页</span>
            </a>
        </li>
    {% endif %}
</ul>
</div>
</div>
        </div>
        <div id="panel-554542">
            <div class="row" style="border: solid 1px #39445c;">
                <div id="main1" style="width:45%;height:500px;float: left;"></div>
                <script>
                var myChart = echarts.init(document.getElementById('main1'));
                option = {
                    title: {
                        text: '各大类型职位占比',
                        x:'center'
                    },
                    tooltip : {
                        trigger: 'item',
                        formatter: "{a} <br/>{b} : {c} ({d}%)"
                    },
                    legend: {
                        orient: 'vertical',
                        left: 'left',
                        data: ['后端开发','移动开发','前端开发','人工智能','测试', '运维', '数据库']
                    },
                    series: [{name:'数目', type:'pie',radius : '55%',center: ['50%', '60%'],
                                itemStyle: {
                                    emphasis: {
                                        shadowBlur: 10,
                                        shadowOffsetX: 0,
                                        shadowColor: 'rgba(0, 0, 0, 0.5)'
                                    }
                                }
                    }]
                };
                myChart.setOption(option);
                myChart.showLoading();
                $.post("{% url 'index' %}", {"type": 1}, function(result){
                     myChart.hideLoading();    //隐藏加载动画
                     myChart.setOption({        //加载数据图表
                                    series: [{name: '数目', data: result.data}]
                                });
                });
            </script>
                <div id="main2" style="width:45%;height:500px;float: left"></div>
                <script>
                    var myChart2 = echarts.init(document.getElementById('main2'));
                    option = {
                        title: {
                            text: '各大职位地区占比',
                            x:'center'
                        },
                        tooltip : {
                            trigger: 'item',
                            formatter: "{a} <br/>{b} : {c} ({d}%)"
                        },
                        legend: {
                            orient: 'vertical',
                            left: 'left',
                            data: []
                        },
                        series: [{name:'数目', type:'pie',radius : '50%',center: ['50%', '60%'],
                                    itemStyle: {
                                        emphasis: {
                                            shadowBlur: 10,
                                            shadowOffsetX: 0,
                                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                                        }
                                    }
                        }]
                    };
                    myChart2.setOption(option);
                    myChart2.showLoading();
                    $.post("{% url 'index' %}", {"type": 2}, function(result){
                         myChart2.hideLoading();    //隐藏加载动画
                         myChart2.setOption({        //加载数据图表
                                        legend:{data:result.locations},
                                        series: [{name: '数目', data: result.data}]
                                    });
                    });
                </script>
            </div>
            <div class="row" style="border: solid 1px #39445c;">
                <div id="main3" style="width:45%;height:500px;float: left;"></div>
                <script>
                var myChart3 = echarts.init(document.getElementById('main3'));
                option = {
                    title: {
                        text: '不同城市薪水趋势图',
                        x:'center'
                    },
                    tooltip : {
                        trigger: 'axis',
                        axisPointer: {
                            type: 'cross',
                            label: {
                                backgroundColor: '#6a7985'
                            }
                        }
                    },
                    yAxis: {
                        type: 'value'
                    },
                    xAxis: {type: 'category',data: []},
                    series: [{
                        name:'平均薪资',
                        data: [],
                        type: 'line'
                    }]
                };
                myChart3.setOption(option);
                myChart3.showLoading();
                $.post("{% url 'index' %}", {"type": 3}, function(result){
                     myChart3.hideLoading();    //隐藏加载动画
                     myChart3.setOption({        //加载数据图表
                                    xAxis:{type: 'category', data:result.locations},
                                    series: [{name: '平均薪资', data: result.money}]
                                });
                });
            </script>
                <div id="main4" style="width:45%;height:500px;float: left"></div>
                <script>
                    var myChart4 = echarts.init(document.getElementById('main4'));
                    option = {
                        title: {
                            text: '公司规模占比',
                            x:'center'
                        },
                        tooltip : {
                            trigger: 'item',
                            formatter: "{a} <br/>{b} : {c} ({d}%)"
                        },
                        legend: {
                            orient: 'vertical',
                            left: 'left',
                            data: []
                        },
                        series: [{name:'数目', type:'pie',radius : '50%',center: ['50%', '60%'],
                                    itemStyle: {
                                        emphasis: {
                                            shadowBlur: 10,
                                            shadowOffsetX: 0,
                                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                                        }
                                    }
                        }]
                    };
                    myChart4.setOption(option);
                    myChart4.showLoading();
                    $.post("{% url 'index' %}", {"type": 4}, function(result){
                         myChart4.hideLoading();    //隐藏加载动画
                         myChart4.setOption({        //加载数据图表
                                        legend:{data:result.rongzi},
                                        series: [{name: '数目', data: result.data}]
                                    });
                    });
                </script>
        </div>
    </div>

{% endblock %}

{% block customjs %}
    <script>
        $(document).ready(function(){
             $("#panel-554542").css("display","none");
          $("#a-554542").click(function(){
            $("#panel-554542").css("display","block");
            $("#panel-8023").css("display","none");
          });
          $("#a-8023").click(function(){
            $("#panel-554542").css("display","none");
            $("#panel-8023").css("display","block");
          });
        });

    </script>

{% endblock %}

templates/index1.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block customstyle %}
    <script type="text/javascript" src="http://libs.baidu.com/jquery/2.1.1/jquery.min.js"></script>
    <script language="JavaScript" type="text/javascript" src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js" charset="utf-8"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <style type="text/css">
        body{overflow-x:hidden; background:#f2f0f5;}
        #main-tab {
            border: 1px solid #eaeaea;
            background: #FFF;
            font-size: 12px;
            margin: auto;
        }
        tbody {
            display: table-row-group;
            vertical-align: middle;
            border-color: inherit;
        }
        tr {
            display: table-row;
            vertical-align: inherit;
            border-color: inherit;
        }
        #main-tab td {
            font-size: 14px;
            line-height: 50px;
        }
        .borderright{ border-right:1px solid #ebebeb}
        .borderbottom{ border-bottom:1px solid #ebebeb}
        table {
            border-collapse:collapse;
            border-spacing:0;
            font-size:14px;
        }
        caption,th {
            text-align:left;
        }
        td.fenye{ padding:10px 0 0 0; text-align:right;}
    </style>
{% endblock %}
{% block content %}
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#panel-8023" id="a-8023" data-toggle="tab">职位查看</a>
        </li>
        <li>
            <a href="#panel-554542" id="a-554542" data-toggle="tab">职位分析</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="panel-8023">
            <div class="row" style="margin-bottom:5px;">
<div>
<table width="80%" border="0" cellspacing="0" cellpadding="0" id="main-tab">
    <th>
        <tr style="background-color: #39445c;color: white;">

            <td align="center" valign="middle" class="borderright borderbottom">职位</td>
            <td align="center" valign="middle" class="borderright borderbottom">薪资范围</td>
            <td align="center" valign="middle" class="borderright borderbottom">公司名称</td>
            <td align="center" valign="middle" class="borderright borderbottom">公司融资</td>
            <td align="center" valign="middle" class="borderright borderbottom">地理位置</td>
            <td align="center" valign="middle" class="borderright borderbottom">工作经验</td>
            <td align="center" valign="middle" class="borderright borderbottom">所属行业</td>
            <td align="center" valign="middle" class="borderright borderbottom">学历</td>
            <td align="center" valign="middle" class="borderright borderbottom">类型</td>
        </tr>
    </th>

    {% for item in paginator.object_list %}
    <tr onMouseOut="this.style.backgroundColor='#ffffff'" onMouseOver="this.style.backgroundColor='#edf5ff'">
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.zhiwei }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.money }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.company_name }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.rongzi }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.position }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.exp }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.industry }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.xueli }}</td>
        <td align="center" valign="middle" class="borderright borderbottom">{{ item.get_skill_type_display}}</td>
    </tr>
    {% endfor %}

</table>
</div>
<div style="width: 80%;margin: auto">
 <ul class="pagination pagination-lg">
    {% if paginator.has_previous %}
        <li>
            <a href="{% url 'index1' %}?page={{ paginator.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">上一页</span>
            </a>
        </li>
    {% else %}
        <li class="disabled">
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">上一页</span>
            </a>
        </li>
    {% endif %}

    {% for number in paginator.paginator.pager_num_range %}
        {% if number == paginator.number %}
            <li class="active"><a href="{% url 'index1' %}?page={{ number }}">{{ number }}</a></li>
        {% else %}
            <li><a href="{% url 'index1' %}?page={{ number }}" >{{ number }}</a></li>
        {% endif %}
    {% endfor %}
    {% if paginator.has_next %}
        <li>
            <a href="{% url 'index1' %}?page={{ paginator.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">下一页</span>
            </a>
        </li>
    {% else %}
        <li class="disabled">
            <a href="#" aria-label="Next">
                <span aria-hidden="true">下一页</span>
            </a>
        </li>
    {% endif %}
</ul>
</div>
</div>
        </div>
        <div id="panel-554542">
            <div class="row" style="border: solid 1px #39445c;">
                <div id="main1" style="width:45%;height:500px;float: left;"></div>
                <script>
                var myChart1 = echarts.init(document.getElementById('main1'));
                option = {
                    title: {
                        text: '不同城市薪水趋势图',
                        x:'center'
                    },
                    tooltip : {
                        trigger: 'axis',
                        axisPointer: {
                            type: 'cross',
                            label: {
                                backgroundColor: '#6a7985'
                            }
                        }
                    },
                    yAxis: {
                        type: 'value'
                    },
                    xAxis: {type: 'category',data: []},
                    series: [{
                        name:'平均薪资',
                        data: [],
                        type: 'line'
                    }]
                };
                myChart1.setOption(option);
                myChart1.showLoading();
                $.post("{% url 'index1' %}", {"type": 1}, function(result){
                     myChart1.hideLoading();    //隐藏加载动画
                     myChart1.setOption({        //加载数据图表
                                    xAxis:{type: 'category', data:result.locations},
                                    series: [{name: '平均薪资', data: result.money}]
                                });
                });
            </script>

                <div id="main2" style="width:45%;height:500px;float: left"></div>
                <script>
                    var myChart2 = echarts.init(document.getElementById('main2'));
                    option = {
                        title: {
                            text: '各大职位地区占比',
                            x:'center'
                        },
                        tooltip : {
                            trigger: 'axis',
                            axisPointer: {
                                type: 'cross',
                                label: {
                                    backgroundColor: '#6a7985'
                                }
                            }
                        },
                        yAxis: {
                            type: 'value'
                        },
                        xAxis: {type: 'category',data: []},
                        series: [{
                            name:'数目',
                            data: [],
                            type: 'bar'
                        }]
                    };
                    myChart2.setOption(option);
                    myChart2.showLoading();
                    $.post("{% url 'index1' %}", {"type": 2}, function(result){
                         myChart2.hideLoading();    //隐藏加载动画
                         myChart2.setOption({        //加载数据图表
                             xAxis: {type: 'category',data: result.locations},
                             series: [{name: '数目', data: result.data}]
                         });
                    });
                </script>
            </div>
            <div class="row" style="border: solid 1px #39445c;">
                <div id="main3" style="width:45%;height:500px;float: left;"></div>
                <script>
                var myChart3 = echarts.init(document.getElementById('main3'));
                option = {
                    title: {
                        text: '工作经验柱状图',
                        x:'center'
                    },
                    tooltip : {
                        trigger: 'axis',
                        axisPointer: {
                            type: 'cross',
                            label: {
                                backgroundColor: '#6a7985'
                            }
                        }
                    },
                    yAxis: {
                        type: 'value'
                    },
                    xAxis: {type: 'category',data: []},
                    series: [{
                        name:'数目',
                        data: [],
                        type: 'bar'
                    }]
                };
                myChart3.setOption(option);
                myChart3.showLoading();
                $.post("{% url 'index1' %}", {"type": 3}, function(result){
                     myChart3.hideLoading();    //隐藏加载动画
                     myChart3.setOption({        //加载数据图表
                                    xAxis:{type: 'category', data:result.exp},
                                    series: [{name: '数目', data: result.data}]
                                });
                });
            </script>
                <div id="main4" style="width:45%;height:500px;float: left"></div>
                <script>
                    var myChart4 = echarts.init(document.getElementById('main4'));
                    option = {
                        title: {
                            text: '学历柱状图',
                            x:'center'
                        },
                        tooltip : {
                            trigger: 'axis',
                            axisPointer: {
                                type: 'cross',
                                label: {
                                    backgroundColor: '#6a7985'
                                }
                            }
                        },
                        yAxis: {
                            type: 'value'
                        },
                        xAxis: {type: 'category',data: []},
                        series: [{
                            name:'数目',
                            data: [],
                            type: 'bar'
                        }]
                    };
                    myChart4.setOption(option);
                    myChart4.showLoading();
                    $.post("{% url 'index1' %}", {"type": 4}, function(result){
                         myChart4.hideLoading();    //隐藏加载动画
                         myChart4.setOption({        //加载数据图表
                                        xAxis:{type: 'category', data:result.xueli},
                                        series: [{name: '数目', data: result.data}]
                                    });
                    });
                </script>
        </div>
    </div>

{% endblock %}

{% block customjs %}
    <script>
        $(document).ready(function(){
             $("#panel-554542").css("display","none");
          $("#a-554542").click(function(){
            $("#panel-554542").css("display","block");
            $("#panel-8023").css("display","none");
          });
          $("#a-8023").click(function(){
            $("#panel-554542").css("display","none");
            $("#panel-8023").css("display","block");
          });
        });

    </script>

{% endblock %}